name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential meson ninja libadwaita-1-dev libgtk-4-dev libjson-glib-dev
      - name: Configure meson
        run: meson setup --reconfigure build
      - name: Build
        run: ninja -C build
      - name: Run (smoke)
        run: |
          test -x build/bac || true
